services:
  vote:
    container_name: vote

    build:
      context: ./vote
    volumes:
      - vote:/app/data
    networks:
      - frontend
      - backend
    ports:
      - "5000:80"  # Assuming you want to expose the vote service

  result:
    container_name: result
    build:
      context: ./result
    command: nodemon server.js
    volumes:
      - result:/app/data
    networks:
      - frontend
      - backend
        
    ports:
      - "5001:80"  # Assuming you want to expose the result service

  worker:
    container_name: worker

    build:
      context: ./worker
    networks:
      - backend
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis

    image: redis:alpine
    networks:
      - backend
    ports:
      - "6379:6379"

  postgres:
    container_name: db

    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

volumes:
  vote:
  result:
  db_data:

networks:
  frontend:
  backend:
